### ISSUE TITLE
[Request] GSlider

### ISSUE THREAD

**Issue by pizzadox9999** [keinhaar/gwtswing#4]
Hi @keinhaar,

could you develop a slider element for gwtswing?
It could be a wrapper around the html slider element.

With best regards pizzadox9999

**Comment by keinhaar** [comment]
Added GSlider to gwtswing. To make that work, i needed some changes to gplatform and it's implementations.
The new GWTSwing GSlider does show up correctly in TeaVM, but if i call getValue() it get's a nullpointer exception.
Doing the same on gplatform.gwt works as expected. The updated showcase shows the problem. If the slider is moved, it should show an alert with the new value. On TeaVM, there is currently only an error in the log.

**Comment by keinhaar** [comment]
Fixed the Slider on TeaVM.
