### ISSUE TITLE
GMouseEvent returns 0 for getX() and getY()

### ISSUE THREAD

**Issue by pizzadox9999** [keinhaar/gwtswing#6]
Hi, the de.exware.gwtswing.awt.event.GMouseEvent returns 0 for the functions getX() and getY(). This is because x is calculated instead of just passed through. `\nx = jsEvent.getClientX() - loc.x - insets.left; \n y = jsEvent.getClientY() - loc.y - insets.top;` I don't know why this is so but the function jsEvent.getClientX() reports the correct pixels, but x stays 0 because of the done with x. Is there a way to "fix" this behaviour?

pizzadox9999

**Comment by keinhaar** [comment]
This does not happen when using the GWT implementation of gplatform.
The calculation is necessary, because in swing, the x/y coordinates of the MouseEvent are relative to the component where it occured. In DOM it is relative to the viewport.

**Comment by pizzadox9999** [comment]
Thank you for the clarification. Is there any particular way in your mind I can reproduce this feature in TeaVM?
Besides that can I ask you how you managed to move the dialog in your demo or should I open a new issue for that?

**Comment by keinhaar** [comment]
i think you need to debug why the x value is set to zero. maybe the location is equal to clientx? or location is not a number?
what do you mean with move the dialog? dialogs are windows, and i implemented it to be moveable by mouse drag.

**Comment by keinhaar** [comment]
I've setup my very first teavm project, and managed to get this code running.
```java
	public static void main(String[] args) {
        TeavmGPlatform.init();
        GPanel panel = new GPanel();
        panel.setLayout(new GGridLayout(1,2));
        panel.setBorder(GBorderFactory.createLineBorder(GColor.BLUE, 2));
        GLabel label = new GLabel("Hallo");
        panel.add(label);
        label = new GLabel("Hallo");
        label.addMouseListener(new GMouseAdapter()
		{
        	@Override
        	public void mouseClicked(GMouseEvent evt) {
        		LOG.log("" + evt.getX());
        	}
		});
        panel.add(label);
        panel.setSize(800,600);
        GUtilities.addToBody(panel);
	int left = label.getPeer().getAbsoluteLeft();
	LOG.log("" + left);
    }
```
GMouseEvent uses GComponents getLocationOnScreen() to calculate the correct values.
In the debugger, i can see, that GComponents getLocationOnScreen() returns an GPoint with undefined values for x and y.
So it looks like the TeavmGPElements getAbsoluteLeft() returns no value?

**Comment by pizzadox9999** [comment]
Yes you are right. I looked into it and it looks like teavm is trying to use a property called absoluteLeft. But this property doesn't seem to exists any more. I used the gwt implementation for getAbsoluteLeft/Top. Now it should return the right values. You can find it in the pull request.

**Comment by pizzadox9999** [comment]
Thank you now it is working. I can move the GPanel around.
